site_name: Pool Playoffs 2024

nav:
  - Home: "index.md"
  - Classement: "rankings.md"
  - Poolers: "poolers.md"

plugins:
  autorefs:
  glightbox:
  search:

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  language: fr
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        accent: purple
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        toggle:
          icon: material/weather-night
          name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: 'material/library'
    repo: 'material/library'
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      data: octicons/database-16
      squirell: octicons/squirrel-16
      goal: octicons/goal-16
      rocket: octicons/rocket-16

extra_css:
- css/mkdocstrings.css
- css/image.css
- css/datatable.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
